import { Command } from 'commander';
import chalk from 'chalk';
import inquirer from 'inquirer';
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';
import yaml from 'yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, '..', '..');

export const configCommand = new Command('config')
  .description('View or edit school configuration')
  .option('--view', 'View current configuration')
  .option('--edit', 'Edit configuration interactively')
  .option('--export <file>', 'Export config to YAML file')
  .option('--import <file>', 'Import config from YAML file')
  .action(async (options) => {
    const configPath = path.join(ROOT_DIR, 'config', 'school.py');
    const frontendConfigPath = path.join(ROOT_DIR, 'frontend', 'src', 'lib', 'school-config.local.ts');

    if (options.view) {
      await viewConfig(configPath, frontendConfigPath);
      return;
    }

    if (options.edit) {
      await editConfig(configPath, frontendConfigPath);
      return;
    }

    if (options.export) {
      await exportConfig(configPath, options.export);
      return;
    }

    if (options.import) {
      await importConfig(options.import, configPath, frontendConfigPath);
      return;
    }

    // Default: show config
    await viewConfig(configPath, frontendConfigPath);
  });

async function viewConfig(backendPath, frontendPath) {
  console.log(chalk.cyan.bold('\n📋 Current School Configuration\n'));

  // Read backend config
  if (await fs.pathExists(backendPath)) {
    const content = await fs.readFile(backendPath, 'utf-8');
    console.log(chalk.bold('Backend (config/school.py):'));
    console.log(chalk.gray(content.substring(0, 500) + '...'));
  }

  // Read frontend config
  if (await fs.pathExists(frontendPath)) {
    const content = await fs.readFile(frontendPath, 'utf-8');
    console.log(chalk.bold('\nFrontend (frontend/src/lib/school-config.local.ts):'));
    console.log(chalk.gray(content.substring(0, 500) + '...'));
  }

  // Show env files status
  console.log(chalk.bold('\nEnvironment Files:'));
  const envFiles = [
    { path: 'backend/.env', label: 'Backend' },
    { path: 'frontend/.env.local', label: 'Frontend' }
  ];
  
  for (const { path: p, label } of envFiles) {
    const fullPath = path.join(ROOT_DIR, p);
    const exists = await fs.pathExists(fullPath);
    console.log(`  ${exists ? chalk.green('✅') : chalk.red('❌')} ${label} (${p})`);
  }
}

async function editConfig(backendPath, frontendPath) {
  console.log(chalk.cyan.bold('\n✏️  Edit School Configuration\n'));

  // Read current config
  let currentConfig = {};
  if (await fs.pathExists(frontendPath)) {
    const content = await fs.readFile(frontendPath, 'utf-8');
    // Parse the exported object (simplified)
    const match = content.match(/export const schoolConfig: SchoolConfig = ({[\s\S]*});/);
    if (match) {
      try {
        currentConfig = eval('(' + match[1] + ')');
      } catch {}
    }
  }

  // Prompt for new values
  const answers = await inquirer.prompt([
    { type: 'input', name: 'name', message: 'School name:', default: currentConfig.name || 'PulseCampus' },
    { type: 'input', name: 'domain', message: 'Domain:', default: currentConfig.domain || 'localhost:3000' },
    { type: 'input', name: 'lat', message: 'Latitude:', default: currentConfig.defaultLat || 37.7245 },
    { type: 'input', name: 'lng', message: 'Longitude:', default: currentConfig.defaultLng || -122.4773 },
    { type: 'input', name: 'primaryColor', message: 'Primary color (hex):', default: currentConfig.primaryColor || '#1e40af', validate: v => /^#[0-9A-Fa-f]{6}$/.test(v) },
    { type: 'input', name: 'secondaryColor', message: 'Secondary color (hex):', default: currentConfig.secondaryColor || '#16a34a', validate: v => /^#[0-9A-Fa-f]{6}$/.test(v) },
    { type: 'input', name: 'logo', message: 'Logo emoji:', default: currentConfig.logoEmoji || '🏫' },
  ]);

  // Update configs
  await writeConfigs({ ...currentConfig, ...answers });
  console.log(chalk.green('\n✅ Configuration updated'));
}

async function writeConfigs(config) {
  // Write frontend config
  const frontendConfigPath = path.join(ROOT_DIR, 'frontend', 'src', 'lib', 'school-config.local.ts');
  const frontendConfigContent = `// Auto-generated by create-pulse-campus config
// Do not edit directly - run create-pulse-campus config instead

import { SchoolConfig } from './school-config';

export const schoolConfig: SchoolConfig = ${JSON.stringify(config, null, 2)};
`;

  await fs.writeFile(frontendConfigPath, frontendConfigContent);

  // Update backend config
  const backendPath = path.join(ROOT_DIR, 'config', 'school.py');
  const backendContent = `from app.school_config import SchoolConfig

SCHOOL_CONFIG = SchoolConfig(
    name="${config.name}",
    short_name="${config.shortName || config.name.replace(/\s+/g, '').substring(0, 20)}",
    domain="${config.domain}",
    default_lat=${config.defaultLat || 37.7245},
    default_lng=${config.defaultLng || -122.4773},
    default_zoom=16,
    buildings=${JSON.stringify(config.buildings || [], null, 4)},
    courses=${JSON.stringify(config.courses || [], null, 4)},
    primary_color="${config.primaryColor || '#1e40af'}",
    secondary_color="${config.secondaryColor || '#16a34a'}",
    logo_emoji="${config.logoEmoji || '🏫'}",
)
`;

  await fs.writeFile(path.join(ROOT_DIR, 'config', 'school.py'), backendContent.trim());
}

async function exportConfig(configPath, outputFile) {
  const outputPath = path.resolve(outputFile);
  const content = await fs.readFile(configPath, 'utf-8');
  await fs.writeFile(outputPath, content);
  console.log(chalk.green(`✅ Config exported to ${outputFile}`));
}

async function importConfig(inputFile, backendPath, frontendPath) {
  const inputPath = path.resolve(inputFile);
  const content = await fs.readFile(inputPath, 'utf-8');
  
  await fs.writeFile(backendPath, content);
  console.log(chalk.green('✅ Config imported'));
  console.log(chalk.yellow('Run create-pulse-campus config --edit to sync frontend'));
}